### ISSUE TITLE
Flight Chart showing old data

### ISSUE THREAD

**Issue by dazzag24** [janhartmann/flight-spotter#1]
Hi,

Great example!  Looks really beautiful.

I deployed it while digging around in the UI I noticed that the flight chart data had timestamps that didn't correlate with now.  
To investigate further I added some day and month info to the tooltip and I see all data is from the 14th March.  
Is this an OpenSky issue?
If so is anyone else observing the same?

Thanks
Darren

**Comment by janhartmann** [comment]
Hi @dazzag24 

Thank you for your interest in the project. There is currently an issue with how the barometric chart data. I have narrowed it down to being a OpenSky API issue. I actually opened an issue at their site: https://opensky-network.org/forum/questions/340-flight-tracks-is-out-of-sync 

This is also the reason why I have disabled the trajectory of the flight, see commented out code: https://github.com/janhartmann/flight-spotter/blob/master/client/src/flights/FlightTrajectoryLayer.tsx 

When the data is in sync again, the trajectory line could be enabled again.

**Comment by dazzag24** [comment]
Thanks.  Lets hope someone from OpenSky answers your question.

**Comment by janhartmann** [comment]
Let me see if I can poke them on Twitter. :-)

**Comment by janhartmann** [comment]
Update from OpenSky Network:

https://twitter.com/OpenSkyNetwork/status/1131818414199201792
